[package]
name = "rp_sandbox_c"
description = "Testing project -- please ignore"
license = "MIT OR Apache-2.0"
version = { workspace = true }
edition = "2021"

[dependencies]
rp_sandbox_a = { path = "../rp_sandbox_a", version = "0.9.0" }
