[package]
name = "rp_sandbox_b"
description = "Testing project -- please ignore"
license = "MIT OR Apache-2.0"
version = "0.14.0"
edition = "2021"

[dependencies]
rp_sandbox_a = { path = "../rp_sandbox_a", version = "0.14.0" }
