name: PR title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  title_cc_validation:
    name: Conventional commits validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          if $(echo "$PR_TITLE" | grep '^chore(\(.*\))\?: release '); then
            echo "OK: chore release pattern"
            exit 0;
          fi

          echo "Didn't match chore pattern"

          set -e
          cargo install commitlint-rs
          echo "$PR_TITLE" | commitlint
