name: PR title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  title_cc_validation:
    name: Conventional commits validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: echo PR title is $PR_TITLE
