name: PR title

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  title_cc_validation:
    name: Conventional commits validation
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Check PR title
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
        run: |
          echo <<EOF
          If this step fails, please change this pull request's title
          to follow Conventional Commit conventions.

          A quick summary of Conventional Commits is here:

            https://www.conventionalcommits.org/en/v1.0.0/#summary

          There are a few additional rules that are enforced in this project:

            * The first word of the description must be capitalized.
            * The description must not end with a period.
            * The "type" must be one of the following exact names:

                * fix
                * feat (will cause a minor version bump)
                * chore (will be omitted from changelog)

            * The scope may be omitted. If it exists, it must be
              one of the following exact names:

                * rp_sandbox_a
                * rp_sandbox_b
                * rp_sandbox_c
          EOF

          if echo "$PR_TITLE" | grep -E '^chore(\(.*\))?: release '; then
            echo "Exception / OK: chore release pattern"
            exit 0;
          fi

          cargo install commitlint-rs
          set -e

          # Workaround for https://github.com/KeisukeYamashita/commitlint-rs/issues/355
          if echo "$PR_TITLE" | grep -E "^[a-z]+\(.*\): "; then
            echo "$PR_TITLE" | commitlint -g .commitlintrc.yml
          else
            echo "$PR_TITLE" | commitlint -g .commitlintrc.no-scope.yml
          fi
