name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest

    outputs:
      release-tag: ${{ steps.sniff-release-tag.outputs.tag }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run release-plz
        id: release-plz
        uses: MarcoIeni/release-plz-action@v0.5.108
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_SECRET }}

      - name: Clean up stale release-plz branches
        run: |
          git --no-pager branch --remote |\
            grep 'origin/release-plz-' |\
            sort -r |\
            tail -n +2 |\
            sed 's/origin\///' |\
            xargs -I {} git push origin --delete {}

      - name: Force update of rp_sandbox-b if only rp_sandbox_a is updated
        if: ${{ contains(steps.release-plz.outputs.releases, 'rp_sandbox_a') && !contains(steps.release-plz.outputs.releases, 'rp_sandbox_b') }}
        run: |
          # Ensure we're on a clean main branch
          git checkout main
          git pull origin main
          
          # Extract the new version of rp_sandbox_a from the release PR output
          NEW_VERSION=$(echo '${{ steps.release-plz.outputs.releases }}' | grep -oE 'rp_sandbox_a-[0-9]+\.[0-9]+\.[0-9]+' | head -1 | sed 's/rp_sandbox_a-//')
          
          # Add a comment to the lib.rs file to trigger a change
          echo "// Updated to use rp_sandbox_a $NEW_VERSION" >> rp_sandbox_b/src/lib.rs
          
          # Configure git and commit the changes
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add rp_sandbox_b/src/lib.rs
          git commit -m "chore: Pick up latest rp_sandbox_a"
          git push origin main

      - name: Identify rp-sandbox-a release
        id: sniff-release-tag
        run: |
            echo tag=`git tag --contains HEAD | grep '^rp_sandbox_a-'` >> "$GITHUB_OUTPUT" || true

  inspect-release:
    name: Inspect recent release
    runs-on: ubuntu-latest
    needs: release-plz

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        if: ${{ needs.release-plz.outputs.release-tag }}

      - name: Debug TAG output
        if: ${{ needs.release-plz.outputs.release-tag }}
        env:
          TAG: ${{ needs.release-plz.outputs.release-tag }}
        run: |
          echo Doing the thing with tag $TAG
