name: Release-plz

permissions:
  pull-requests: write
  contents: write

on:
  push:
    branches:
      - main

jobs:
  release-plz:
    name: Release-plz
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.RELEASE_PLZ_TOKEN }}

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Run release-plz
        run: |
          cargo install --git https://github.com/scouten-adobe/release-plz.git --branch features_always_increment_minor release-plz
          release-plz release-pr --git-token ${{ secrets.RELEASE_PLZ_TOKEN }}
          release-plz release --git-token ${{ secrets.RELEASE_PLZ_TOKEN }}
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}

      # - name: Run release-plz
      # # (Restore this when/if https://github.com/MarcoIeni/release-plz/pull/1657
      # #  is merged.)
      #   uses: MarcoIeni/release-plz-action@v0.5
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.RELEASE_PLZ_TOKEN }}
      #     CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
